version: '3.4'

services:
  kitalatala:
    image: kitalatala
    working_dir: /app
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:3000
    restart: always
    volumes:
      - .:/app
      - '/app/node_modules'
